### ISSUE TITLE
Support for post-concatenation plugins

### ISSUE THREAD

**Issue by alexlafroscia** [salsify/broccoli-css-modules#3] opened 2016-12-22 06:29 UTC
I'm trying to get `ember-css-modules` working with `postcss-sprites` and it's been quite a hassle.  The specific issue that I'm facing is already tracked in that repo by https://github.com/2createStudio/postcss-sprites/issues/69, but it doesn't look like a good solution will be available anytime soon.

The issue could be solved if there was a way to specify `postcss` plugins that run after concatenation. Would you be open to a PR that adds that ability?

**Comment by dfreeman** [comment] 2016-12-22 06:54
I'm definitely on board with the idea (you're not the first person to hit this), but the final concatenation actually happens [over in ember-css-modules](https://github.com/salsify/ember-css-modules/blob/master/lib/output-styles-preprocessor.js) — this package only handles the per-module stuff.

I _think_ now that https://github.com/salsify/ember-css-modules/pull/58 has landed, you could run `postcss-sprites` via `ember-cli-postcss` on the concatenated output, but having a baked-in, documented `postprocess` set of plugins would be much nicer.

Would you be up for tackling that in `ember-css-modules`? It would likely involve conditionally running [this tree](https://github.com/salsify/ember-css-modules/blob/master/lib/output-styles-preprocessor.js#L27) through something like broccoli-postcss if any postprocess plugins are configured.

**Comment by alexlafroscia** [comment] 2016-12-22 07:02
Yup! I wasn't 100% sure what the right level to introduce this would be.

Thanks for the pointer on where to start looking.  I'll get a PR together tomorrow.

**Comment by alexlafroscia** [comment] 2016-12-22 20:34
So, I have an initial version of this working here:

https://github.com/alexlafroscia/ember-css-modules/tree/add-postprocess-plugin-set

The problem is that it relies on `broccoli-postcss`, which uses a different syntax for specifying the plugins, which looks like this:

```json
[
  {
    module: require('autoprefixer'),
    options: { ... }
  },
  ...
]
```

Which means that the syntax, if using `before` and `after` and `postprocess` is kind of mixed

<img width="620" alt="screen shot 2016-12-22 at 12 25 34 pm" src="https://cloud.githubusercontent.com/assets/1645881/21439438/f0195670-c842-11e6-9719-36a4a8d8856b.png">

How would you feel about supporting the `{ module: ... , options ... }` syntax in the other two locations, so that it could all be consistent?  The alternative is creating a fork of `broccoli-postcss` and depending on that.

**Comment by dfreeman** [comment] 2016-12-23 03:29
I don't totally understand why broccoli-postcss is doing what it's doing with the `module`/`options` dance (looks like it's something to do with copying config around?), but it looks like @jasonmit's branch [here](https://github.com/alexlafroscia/ember-css-modules/pull/1) switches over to `broccoli-persistent-filter` + `postcss`, which solves the consistency problem, right?

(Edit: and now I see you've merged that in since I last looked 🙂)

**Comment by alexlafroscia** [comment] 2016-12-23 03:32
Yeah! @jasonmit and I work together, so he's been helping me with this 😀

I agree, it's a bit weird that `broccoli-postcss` differs from the "regular" syntax without a great reason.  Not sure why that's necessary, but Jason's plugin seems to be exactly what I'm looking for.

**Comment by alexlafroscia** [comment] 2016-12-23 03:58
@dfreeman do you have ideas on how I should set up tests for this new feature?

**Comment by dfreeman** [comment] 2016-12-23 04:11
That's an excellent question. We briefly had Nodeland tests for the template transform in ember-css-modules, but ended up converting them to run in the browser when the Glimmer 2 alpha rolled out in order to use the rendering engine that was actually packaged with each version of Ember.

I think explicit tests for the postcss-persistent-filter would be useful to have, which probably means bringing back a Node test runner — the Mocha set up in this repo is probably relatively similar to what you'd want. Beyond that, some kind of smoke test to verify it actually works live (e.g. by adding a postprocess plugin to the dummy app and verifying it gets run) could prevent any careless regressions in the future.

**Comment by alexlafroscia** [comment] 2016-12-23 04:19
Cool. I'll add those things a part of my PR. Might be a few days, I'm traveling for the holidays.

**Comment by dfreeman** [comment] 2016-12-23 04:32
Sounds good! Feel free to ping me here or on Slack if there's anything I can do to help out — I'm traveling as well so may not be able to respond right away, but I'm super happy to have another dev getting some familiarity with the ECM codebase.

**Closed as completed** 2017-08-16 18:51 UTC
